### ISSUE TITLE
Python 3 compatibility of tee.py

### ISSUE THREAD

**Issue by OshinoMoumou** [RudolfCardinal/pythonlib#6]
Hello!
I noticed that cardinal_pythonlib/tee.py quoted coded from StackOverflow, and the [original post](https://stackoverflow.com/posts/4985080/revisions) has been revised for python 3 compatibility. Would it cause problem for your code? 
Also, in file openxml/find_recovered_openxml.py  a post was quoted and under that post a [comment](https://stackoverflow.com/questions/6126007/python-getting-a-traceback-from-a-multiprocessing-process/26096355#comment107573798_26096355) pointed out some kind of problem. Will that cause errors?
Have a nice day!

**Comment by RudolfCardinal** [comment]
Dear OshinoMoumou,
It definitely works already under Python 3. Do let me know if you find a problem in the code here.
All the best,
Rudolf
